export {
  useReadingPrefs,
  ReadingPrefsProvider,
  FONT_SIZE_DEFAULT,
  FONT_SIZE_MIN,
  FONT_SIZE_MAX,
  LINE_SPACING_PRESETS,
  LINE_SPACING_DEFAULT,
  CONTENT_WIDTH_DEFAULT,
  FONT_FAMILY_DEFAULT,
  type LineSpacing,
  type ContentWidth,
  type FontFamily,
  type ReadingPrefs,
} from "@/context/ReadingPrefsContext";
