import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1 },
  center: { alignItems: "center", justifyContent: "center", gap: 12 },
  webview: { flex: 1 },
  metaSection: {
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  tagsRow: {
    paddingVertical: 10,
  },
  tagsScroll: {
    paddingHorizontal: 16,
    gap: 8,
  },
  tagChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
  },
  tagChipText: { fontSize: 13 },
  relatedSection: {
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingTop: 12,
    paddingHorizontal: 16,
    paddingBottom: 4,
  },
  relatedLabel: {
    fontSize: 11,
    letterSpacing: 1.2,
    marginBottom: 8,
  },
  relatedRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    marginBottom: 6,
    gap: 8,
  },
  relatedContent: { flex: 1 },
  relatedTitle: { fontSize: 14, lineHeight: 20, marginBottom: 2 },
  relatedCat: { fontSize: 12 },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  openBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 8,
    paddingVertical: 13,
    paddingHorizontal: 20,
    marginBottom: 4,
  },
  openBtnText: { color: "#ffffff", fontSize: 15 },
  errorText: { fontSize: 16, marginTop: 8 },
  resumeBanner: {
    flexDirection: "column",
    borderRadius: 10,
    borderWidth: 1,
    paddingVertical: 11,
    paddingHorizontal: 14,
  },
  swipeHintHandle: {
    alignSelf: "center",
    marginTop: 6,
    width: 28,
    height: 3,
    borderRadius: 2,
  },
  resumeBannerText: {
    flex: 1,
    fontSize: 13,
  },
  shareQuoteBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 16,
    marginBottom: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
  },
  shareQuoteBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 7,
  },
  shareQuoteBtnText: {
    color: "#ffffff",
    fontSize: 13,
  },
  shareQuoteTooLong: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 4,
    paddingVertical: 6,
  },
  shareQuoteTooLongText: {
    fontSize: 12,
    flexShrink: 1,
  },
  shareQuotePreview: {
    flex: 1,
    fontSize: 12,
    fontStyle: "italic",
  },
  copyToast: {
    position: "absolute",
    bottom: 90,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(30,30,30,0.88)",
    paddingVertical: 9,
    paddingHorizontal: 16,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  copyToastText: {
    color: "#ffffff",
    fontSize: 13,
  },
});
